# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cowtech-rails}
  s.version = "1.0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shogun"]
  s.date = %q{2011-04-05}
  s.description = %q{A general purpose Rails utility plugin.}
  s.email = %q{shogun_panda@me.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/helpers/cowtech/application_helper.rb",
    "app/helpers/cowtech/crud_helper.rb",
    "app/helpers/cowtech/format_helper.rb",
    "app/helpers/cowtech/validation_helper.rb",
    "app/models/e_mail.rb",
    "app/models/model_base.rb",
    "config/initializers/extensions.rb",
    "lib/cowtech.rb",
    "lib/engine.rb",
    "lib/extensions.rb",
    "lib/monkey_patches.rb",
    "lib/version.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/ShogunPanda/cowtech-rails}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A general purpose Rails utility plugin.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

